tap "hashicorp/tap"
tap 'homebrew/bundle'

# fs/network
brew "tree"

# search/grep/diff
brew "fzf"
brew "jq"
brew "autojump"
brew "ripgrep"

# sync data
brew "rsync"

# languages/tools
brew "fnm"
brew "go"

# terminal
brew "tmux"

# kubernetes
brew "k9s"
brew "kubectl"
brew "kubectx"
brew "minikube"

# hashicorp
brew "terraform"

# protocol buffer
brew "protobuf"
